### ISSUE TITLE
v1.0.0 TODO List

### ISSUE THREAD

**Issue by jordanbtucker** [json5/json5-spec#1]
- [x] Explain JSON5 features in detail.
- [x] Explain JSON5's handling of `\u2028` and `\u2029`.
- [x] Explain caveats like duplicate property names.
- [x] Move spec to HTML/XML since LaTeX is somewhat esoteric.
